services:
  mattermost:
    image: mattermost/mattermost-team-edition
    ports:
      - "8065:8065"
    environment:
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable"
    volumes:
      - mattermost_data:/mattermost/data
      - mattermost_config:/mattermost/config
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mmuser_password
      POSTGRES_DB: mattermost
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  mattermost_data:
  mattermost_config:
  postgres_data: